### ISSUE TITLE
v1 model description for workspace childrens 

### ISSUE THREAD

**Issue by ybegus** [nicko7i/vcnc#16]
My concern was about v1.
http://cnc:7230/v1/doc/api/?url=spec#!/vTRQ_Workspaces/vtrqWorkspaceChildren
inline_model_16 describes children as an array of workspaces and each workspace contains name and WorkspaceSpec. However actual response is a list of workspace names only. It sounds inconsistent for me. What do you think?

**Comment by nicko7i** [comment]
Oh, yeah, you're right.  I started working on v2 inside the v1 file (because I thought they would be compatible) but they weren't.  When I unwound the changes, I didn't unwind far enough.

A righteous find, Yefim.
