### ISSUE TITLE
One config yaml file for all of vcnc-server

### ISSUE THREAD

**Issue by nicko7i** [nicko7i/vcnc#53]
Our policy is that vcnc-server looks like a single thing at the devops level.  One .service file, one conf.yaml file.

Currently, vcnc-sampler has a different .yaml file for vcnc-sampler.

This issue calls for migrating the vcnc-sampler settings to `vcnc-server/config/vcnc-config.yaml` and deleting the vcnc-sampler config.yaml file.

Although the design intent was that all configuration went though `vcnc-core/src/lib/configuration.js`, it is OK to continue to use the vcnc-sampler configuration module for now.

**Comment by ybegus** [comment]
All sampling parameters are in  vcnc-server/config/vcnc-config.yaml. I didn't use any other yaml file. Where did you find it?

**Comment by nicko7i** [comment]
Aaack!!  My mistake.  No change needed.  Closing this issue.
